# Generated by Django 5.0.4 on 2024-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_done',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Дата окончания'),
        ),
    ]
